# Generated by Django 2.1.3 on 2018-11-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0004_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='property_name',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
