# Generated by Django 2.1.3 on 2018-11-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesapp', '0007_auto_20181125_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner_emailid',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='owner_phone',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
